# Generated by Django 6.0 on 2026-04-21 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0002_deuda_monto_pagado_alter_transaccion_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='categoria',
            field=models.CharField(choices=[('Comida', 'Comida y Supermercado'), ('Transporte', 'Transporte y Gasolina'), ('Servicios', 'Luz, Agua, Internet'), ('Ocio', 'Entretenimiento y Salidas'), ('Salud', 'Salud y Farmacia'), ('Otros', 'Otros Gastos')], default='Otros', max_length=50),
        ),
    ]
