# Generated by Django 6.0 on 2026-04-21 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0003_alter_transaccion_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='deuda',
            name='categoria',
            field=models.CharField(choices=[('Comida', 'Comida y Supermercado'), ('Transporte', 'Transporte y Gasolina'), ('Servicios', 'Luz, Agua, Internet'), ('Ocio', 'Entretenimiento y Salidas'), ('Salud', 'Salud y Farmacia'), ('Otros', 'Otros Gastos')], default='Otros', max_length=50),
        ),
    ]
