# Generated by Django 6.0 on 2026-04-29 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0005_metaahorro_presupuesto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.RemoveField(
            model_name='deuda',
            name='monto_pagado',
        ),
        migrations.AddField(
            model_name='metaahorro',
            name='fecha_limite',
            field=models.DateField(blank=True, help_text='Fecha en que quieres lograr la meta (opcional)', null=True),
        ),
    ]
