# Generated by Django 6.0 on 2026-05-06 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0007_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ciudad',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='moneda',
            field=models.CharField(choices=[('CLP', 'Peso Chileno ($)'), ('USD', 'Dólar Americano (USD)'), ('EUR', 'Euro (EUR)'), ('ARS', 'Peso Argentino ($)'), ('MXN', 'Peso Mexicano ($)'), ('COP', 'Peso Colombiano ($)'), ('PEN', 'Sol Peruano (S/)'), ('BRL', 'Real Brasileño (R$)')], default='CLP', max_length=5),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nombre_completo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pais',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='telefono',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
