# Generated by Django 6.0 on 2026-05-06 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0008_userprofile_ciudad_userprofile_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deuda',
            name='categoria',
            field=models.CharField(choices=[('Comida', 'Comida y Supermercado'), ('Transporte', 'Transporte y Gasolina'), ('Servicios', 'Luz, Agua, Internet'), ('Ocio', 'Entretenimiento y Salidas'), ('Salud', 'Salud y Farmacia'), ('Otros', 'Otros Gastos'), ('Sueldo', 'Sueldo o salario'), ('Freelance', 'Trabajo freelance'), ('Negocio', 'Negocio o emprendimiento'), ('Venta', 'Venta de algo'), ('Bono', 'Bono o aguinaldo'), ('Transferencia', 'Transferencia recibida'), ('Otros_Ingresos', 'Otros ingresos')], default='Otros', max_length=50),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='categoria',
            field=models.CharField(choices=[('Comida', 'Comida y Supermercado'), ('Transporte', 'Transporte y Gasolina'), ('Servicios', 'Luz, Agua, Internet'), ('Ocio', 'Entretenimiento y Salidas'), ('Salud', 'Salud y Farmacia'), ('Otros', 'Otros Gastos'), ('Sueldo', 'Sueldo o salario'), ('Freelance', 'Trabajo freelance'), ('Negocio', 'Negocio o emprendimiento'), ('Venta', 'Venta de algo'), ('Bono', 'Bono o aguinaldo'), ('Transferencia', 'Transferencia recibida'), ('Otros_Ingresos', 'Otros ingresos')], default='Otros', max_length=50),
        ),
    ]
