# Generated by Django 6.0 on 2026-05-06 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0009_alter_deuda_categoria_alter_transaccion_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='es_cuota',
            field=models.BooleanField(default=False),
        ),
    ]
