# Generated by Django 6.1 on 2026-08-19 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0013_gastopendiente'),
    ]

    operations = [
        migrations.AddField(
            model_name='gastopendiente',
            name='transaccion',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gasto_pendiente', to='finanzas.transaccion'),
        ),
    ]
