# Generated by Django 6.0 on 2026-08-19 23:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0014_gastopendiente_transaccion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('categoria', models.CharField(blank=True, default='Suscripciones', max_length=50)),
                ('dia_cobro', models.IntegerField(default=1, help_text='Día del mes en que se cobra (1-28)')),
                ('activa', models.BooleanField(default=True)),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now)),
                ('fecha_cancelada', models.DateField(blank=True, null=True)),
                ('ultimo_mes_generado', models.IntegerField(default=0)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suscripciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-activa', 'nombre'],
            },
        ),
    ]
