# Generated by Django 6.0 on 2026-08-25 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0015_suscripcion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deuda',
            options={'ordering': ['fecha_inicio', 'id']},
        ),
        migrations.AlterModelOptions(
            name='transaccion',
            options={'ordering': ['-fecha', '-id']},
        ),
    ]
