# Generated by Django 6.0 on 2026-08-28 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0104_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='categoria',
            field=models.CharField(choices=[('Comida', 'Comida y Supermercado'), ('Transporte', 'Transporte y Gasolina'), ('Servicios', 'Luz, Agua, Internet'), ('Ocio', 'Entretenimiento y Salidas'), ('Salud', 'Salud y Farmacia'), ('Tecnologia', 'Tecnología y electrónica'), ('Ropa', 'Ropa y calzado'), ('Hogar', 'Hogar y muebles'), ('Viajes', 'Viajes y pasajes'), ('Compras', 'Compras online'), ('Educacion', 'Educación y cursos'), ('Otros', 'Otros Gastos'), ('Sueldo', 'Sueldo o salario'), ('Freelance', 'Trabajo freelance'), ('Negocio', 'Negocio o emprendimiento'), ('Venta', 'Venta de algo'), ('Bono', 'Bono o aguinaldo'), ('Transferencia', 'Transferencia recibida'), ('Otros_Ingresos', 'Otros ingresos')], default='Otros', max_length=50),
        ),
    ]
