# Generated by Django 6.0 on 2026-09-03 15:02

import finanzas.models
import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0106_dos_pasos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='categoria',
            field=models.CharField(choices=[('Comida', 'Comida y Supermercado'), ('Transporte', 'Transporte y Gasolina'), ('Servicios', 'Luz, Agua, Internet'), ('Ocio', 'Entretenimiento y Salidas'), ('Salud', 'Salud y Farmacia'), ('Tecnologia', 'Tecnología y electrónica'), ('Ropa', 'Ropa y calzado'), ('Hogar', 'Hogar y muebles'), ('Viajes', 'Viajes y pasajes'), ('Compras', 'Compras online'), ('Educacion', 'Educación y cursos'), ('Otros', 'Otros Gastos'), ('Sueldo', 'Sueldo o salario'), ('Freelance', 'Trabajo freelance'), ('Negocio', 'Negocio o emprendimiento'), ('Venta', 'Venta de algo'), ('Bono', 'Bono o aguinaldo'), ('Transferencia', 'Transferencia recibida'), ('Otros_Ingresos', 'Otros ingresos')], default='Otros', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='foto',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(access_key='18dee3fc1f42ba24be7620f6ca9ab52a', bucket_name='finapp', custom_domain='pub-c4d49337b6f441f0acfcb0e8229e27e4.r2.dev', endpoint_url='https://223db563a6d18d9d16e20d340d0b05fd.r2.cloudflarestorage.com', file_overwrite=False, object_parameters={'CacheControl': 'public, max-age=31536000'}, querystring_auth=False, region_name='auto', secret_key='493cc6b21ce27734277085d336735c5ec3972463e9559db0c6a455d21d2b68ed'), upload_to=finanzas.models._ruta_avatar),
        ),
    ]
