# Generated by Django 6.0 on 2026-09-03 15:02
#
# EDITADA A MANO. makemigrations congeló aquí el objeto S3Storage completo,
# con la clave de acceso y la clave secreta de R2 en texto plano. Un campo
# storage no afecta al esquema de la base — es solo metadato del histórico —
# así que apuntarlo al callable obtener_almacen (lo mismo que hace 0108) deja
# la migración equivalente y sin secretos.
#
# Esto NO recupera las claves filtradas: siguen en el histórico de git. Hay
# que rotarlas en Cloudflare. Ver AUDITORIA-SEGURIDAD.md.

import finanzas.almacenamiento
import finanzas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0106_dos_pasos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='categoria',
            field=models.CharField(choices=[('Comida', 'Comida y Supermercado'), ('Transporte', 'Transporte y Gasolina'), ('Servicios', 'Luz, Agua, Internet'), ('Ocio', 'Entretenimiento y Salidas'), ('Salud', 'Salud y Farmacia'), ('Tecnologia', 'Tecnología y electrónica'), ('Ropa', 'Ropa y calzado'), ('Hogar', 'Hogar y muebles'), ('Viajes', 'Viajes y pasajes'), ('Compras', 'Compras online'), ('Educacion', 'Educación y cursos'), ('Otros', 'Otros Gastos'), ('Sueldo', 'Sueldo o salario'), ('Freelance', 'Trabajo freelance'), ('Negocio', 'Negocio o emprendimiento'), ('Venta', 'Venta de algo'), ('Bono', 'Bono o aguinaldo'), ('Transferencia', 'Transferencia recibida'), ('Otros_Ingresos', 'Otros ingresos')], default='Otros', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='foto',
            field=models.ImageField(
                blank=True, null=True,
                storage=finanzas.almacenamiento.obtener_almacen,
                upload_to=finanzas.models._ruta_avatar),
        ),
    ]
