# Generated by Django 6.0 on 2026-09-03 19:26

import finanzas.almacenamiento
import finanzas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0107_alter_transaccion_categoria_alter_userprofile_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='foto',
            field=models.ImageField(blank=True, null=True, storage=finanzas.almacenamiento.obtener_almacen, upload_to=finanzas.models._ruta_avatar),
        ),
    ]
